FROM <%= registry %>/baseimage-js8.11.4-rb2.5.1

CMD ["ruby", "/entrypoint"]
<%= dockerfile_entrypoint_at_commit '7170f0f34e4d6cafada7adc5ba6b0f89ac35d39c' %>

RUN pip install --upgrade pip &&\
  pip install supervisor

RUN npm install -g npm@6.3.0
COPY app/package.json app/package-lock.json /
RUN npm install

<%= sources_for_dockerfile :app %>
<%= git_info_for_dockerfile %>

WORKDIR /app
