# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'awesome_print', '~> 1.8'
gem 'aws-sdk-cloudformation', '~> 1.6'
gem 'aws-sdk-cognitoidentityprovider', '~> 1.5'
gem 'colorize', '~> 0.8.1'
gem 'mechanize', '~> 2.7'
gem 'oauth2', '~> 1.4'
gem 'redis', '~> 3.3', '>= 3.3.5'
gem 'rest-client', '~> 2.0', '>= 2.0.2'
gem 'terminal-table', '~> 1.8'
gem 'thor', '~> 0.20.0'
